import java.io.*;
 public class Kitchenware
{
public void kitelec()throws IOException
{BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
Flip obj5=new Flip();
int co,cou;
System.out.print('\u000C');
System.out.println("Samsung fridge FW800                             \t product costs   Rs.20,000");
System.out.println("Samsung fridge FW850                             \t product costs   Rs.25,000");
System.out.println("Samsung fridge FW900                             \t product costs   Rs.50,000");
System.out.println("LG fridge FWL90                                  \t product costs   Rs.15,000");
System.out.println("LG fridge FWL83                                  \t product costs   Rs.10,000");
System.out.println("LG fridge FWL78                                  \t product costs   Rs.30,000");
System.out.println("Samsung microwave oven MO120H                    \t product costs   Rs.5,000");
System.out.println("Samsung microwave oven MO150I                    \t product costs   Rs.7,000");
System.out.println("Samsung microwave oven MO780L                    \t product costs   Rs.8,000");
System.out.println("LG microwave oven MOL90                          \t product costs   Rs.4,000");
System.out.println("LG microwave oven MOL750                         \t product costs   Rs.2,000");
System.out.println("LG microwave oven MOL900                         \t product costs   Rs.10,000");
System.out.println("Onida microwave oven OMO7                        \t product costs   Rs.3,000");
System.out.println("Onida microwave oven OMO8                        \t product costs   Rs.1,500");
System.out.println("Onida microwave oven OMO1                        \t product costs   Rs.6,000");
System.out.println("prestige Meltallic silver stove PR890            \t product costs   Rs.2,000");
System.out.println("prestige Meltallic gold stove PR899              \t product costs   Rs.8,000");
System.out.println("prestige Meltallic user stove PR8959             \t product costs   Rs.5,000");
System.out.println("prestige glass shot  stove PRGS560               \t product costs   Rs.7,000");
System.out.println("prestige glass shot stove PRGS920                \t product costs   Rs.9,000");
System.out.println("prestige pure glass stove PRGS230                \t product costs   Rs.15,000");
System.out.println("prestige induction glass shot stove PRINGS15     \t product costs   Rs.10,000");
System.out.println("prestige induction pure glass shot stove PRINGS28\t product costs   Rs.20,000");
System.out.println("prestige Meltallic induction stove PRINM78       \t product costs   Rs.6,000");
System.out.println("prestige Meltallic gold induction stove PRIMG90  \t product costs   Rs.7,000");
System.out.println("prestige uniform induction stove PRUIS888        \t product costs   Rs.5,000");
System.out.println("prestige fast induction stove PRFIS8954          \t product costs   Rs.3,000");
System.out.println("");System.out.println("Press 1 to add to cart or 2 to go back to the previous menu");
co=Integer.parseInt(br.readLine());
if(co==1){Add obj=new Add();obj.add();
System.out.println("Press 1 to add more or 2 to bill and exit or 3  to cancel bill and exit ");
cou=Integer.parseInt(br.readLine());
if(cou==1){obj5.kit();}else if(cou==2)obj.bill();
else if (cou==3)System.exit(0);	}else if(co==2)obj5.kit();}
public void kitutil()throws IOException
{BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
Flip obj5=new Flip();
int co,cou;
System.out.print('\u000C');
System.out.println("prestige electric cooker C290     \t product costs   Rs.6,000");
System.out.println("prestige electric cooker C890     \t product costs   Rs.5,000");
System.out.println("prestige induction (cooker 1)     \t product costs   Rs.3,000");
System.out.println("prestige induction (cooker 2)     \t product costs   Rs.1,500");
System.out.println("prestige gas (cooker 3)           \t product costs   Rs.3,000");
System.out.println("prestige gas (cooker 4)           \t product costs   Rs.4,000");
System.out.println("prestige air frier AIR889FRY      \t product costs   Rs.25,000");
System.out.println("prestige air frier AIR362FRY      \t product costs   Rs.27,000");
System.out.println("prestige deep fry (pan 1)         \t product costs   Rs.500");
System.out.println("prestige deep fry (pan 2)         \t product costs   Rs.200");
System.out.println("prestige deep fry (pan 3)         \t product costs   Rs.150");
System.out.println("prestige deep fry (pan 4)         \t product costs   Rs.115");
System.out.println("prestige roti (pan 5)             \t product costs   Rs.149");
System.out.println("prestige roti (pan 6)             \t product costs   Rs.163");
System.out.println("prestige roti (pan 7)             \t product costs   Rs.1,000");
System.out.println("prestige roti (pan 8)             \t product costs   Rs.2,500");
System.out.println("prestige roti (pan 9)             \t product costs   Rs.700");
System.out.println("prestige roti (pan 10)            \t product costs   Rs.900");
System.out.println("prestige (spoon 1)                \t product costs   Rs.10 (per set)");
System.out.println("prestige (spoon 2)                \t product costs   Rs.20 (per set)");
System.out.println("prestige (spoon 3)                \t product costs   Rs.50 (per set)");
System.out.println("prestige (spoon 4)                \t product costs   Rs.80 (per set)");
System.out.println("prestige (spoon 5)                \t product costs   Rs.100 (per set)");
System.out.println("prestige (plate 1)                \t product costs   Rs.70 (per set)");
System.out.println("prestige (plate 2)                \t product costs   Rs.100 (per set)");
System.out.println("prestige (plate 3)                \t product costs   Rs.120 (per set)");
System.out.println("prestige (plate 4)                \t product costs   Rs.250 (per set)");
System.out.println("prestig (cups 1)                  \t product costs   Rs.150 (per set)");
System.out.println("prestig (cups 2)                  \t product costs   Rs.200 (per set)");
System.out.println("prestig (cups 3)                  \t product costs   Rs.250 (per set)");
System.out.println("prestig (cups 4)                  \t product costs   Rs.300 (per set)");
System.out.println("drinking (glass 1)                \t product costs   Rs.500 (per set)");
System.out.println("drinking (glass 2)                \t product costs   Rs.650 (per set)");
System.out.println("drinking (glass 3)                \t product costs   Rs.300 (per set)");
System.out.println("");System.out.println("Press 1 to add to cart or 2 to go back to the previous menu");
co=Integer.parseInt(br.readLine());
if(co==1){Add obj=new Add();obj.add();
System.out.println("Press 1 to add more or 2 to bill and exit or 3  to cancel bill and exit ");
cou=Integer.parseInt(br.readLine());
if(cou==1){obj5.kit();}else if(cou==2)obj.bill();
else if (cou==3)System.exit(0);	}else if(co==2)obj5.kit();}
}
